version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: America/Sao_Paulo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: netlify-cli
    versions:
    - 3.10.0
    - 3.10.10
    - 3.10.11
    - 3.10.12
    - 3.10.2
    - 3.10.3
    - 3.10.5
    - 3.10.6
    - 3.10.8
    - 3.11.1
    - 3.13.1
    - 3.13.10
    - 3.13.3
    - 3.13.5
    - 3.13.6
    - 3.13.7
    - 3.13.8
    - 3.13.9
    - 3.14.0
    - 3.15.1
    - 3.15.2
    - 3.16.1
    - 3.17.0
    - 3.17.1
    - 3.17.2
    - 3.18.2
    - 3.19.0
    - 3.20.0
    - 3.21.11
    - 3.21.13
    - 3.21.3
    - 3.21.6
    - 3.23.0
    - 3.4.6
    - 3.4.7
    - 3.5.0
    - 3.6.0
    - 3.7.1
    - 3.8.1
    - 3.8.3
    - 3.8.4
    - 3.8.5
    - 3.8.6
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
    - 6.6.0
    - 6.7.1
    - 6.8.0
    - 7.0.0
    - 7.0.1
    - 7.1.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  registries:
  - npm-registry-npm-pkg-github-com
