name: Test Pull Request

on: [pull_request]

env:
  GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          node_modules-

    - name: Cache NextJS
      uses: actions/cache@v2
      with:
        path: .next/cache
        key: nextjs-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          nextjs-

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        build: yarn build
        start: yarn start
